name: Auto Deployment

on:
  push:
    branches: [ woof ]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    - name: Push to the Docker Hub
      uses: docker/build-push-action@v2
      with:
        context: .
        platforms: linux/amd64, linux/arm64
        push: true
        tags: lilingxi01/docker-woof:latest, lilingxi01/docker-woof:0.${{ github.run_number }}
